name: 更新 Clash 订阅

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: 安装依赖
      run: pip install pyyaml
    
    - name: 运行转换脚本
      run: python scripts/converter.py
    
    - name: 提交更新
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        git diff --staged --quiet || git commit -m "更新 base64 订阅: $(date +'%Y-%m-%d')"
        git push
