name: 更新订阅源

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行（保留原机制）
  push:
    paths:
      - 'sources/base-urls.txt'  # 只在 base-urls.txt 修改时触发（添加新源）
  workflow_dispatch:  # 手动触发（可选）

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: 运行转换脚本
      run: python scripts/converter.py
    - name: 提交更新
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # 强制添加 output/（忽略 .gitignore）
        git add -f output/
        # 检查是否有变化再 commit（避免空 commit）
        if git diff --staged --quiet; then
          echo "无变化，跳过 commit"
          exit 0
        fi
        git commit -m "更新 base64 订阅源: $(date +'%Y-%m-%d')"
        git push
